# Generated by Django 3.0.7 on 2020-06-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github_url',
            field=models.URLField(default='n/a'),
        ),
    ]
